-- ============================================================================
-- cPanel Cert DB — Seed Data (HAND-MAINTAINED — DO NOT OVERWRITE WITH DUMP)
-- ============================================================================
-- This file is NEVER regenerated by mysqldump. Schema dumps go into
--   cpanel-cert-db-install.sql  (safe to overwrite with a fresh dump)
-- Seed rows live ONLY here.
--
-- Run order on a fresh cPanel database:
--   1. Import cpanel-cert-db-install.sql  (schema)
--   2. Import cpanel-cert-db-seed.sql     (this file — required seed rows)
--
-- All statements below are idempotent (ON DUPLICATE KEY UPDATE), so
-- re-running this file is always safe.
-- ============================================================================

-- Seed organization: Lyceum of Alabang (matches DatabaseSeeder + CERT_ORGANIZATION_ID)
INSERT INTO `organizations` (`id`, `name`, `slug`, `website`, `created_at`, `updated_at`)
VALUES ('00000000-0000-0000-0000-000000000001', 'Lyceum of Alabang', 'loa-e-cert', 'https://staging-loa-vericert.vercel.app', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `name` = 'Lyceum of Alabang',
  `slug` = 'loa-e-cert',
  `website` = 'https://staging-loa-vericert.vercel.app',
  `updated_at` = NOW();
