<?php

namespace App\Http\Controllers;

use App\Models\Permission;
use App\Models\Tenant;
use App\Models\User;
use App\Models\UserGroup;
use App\Services\AuthorizationService;
use App\Services\IdentityService;
use App\Services\PasswordResetNotificationService;
use App\Services\TenantService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;
use Illuminate\View\View;

class WebAdminController extends Controller
{
    public function __construct(
        private readonly IdentityService $identity,
        private readonly AuthorizationService $authorization,
        private readonly TenantService $tenants,
        private readonly PasswordResetNotificationService $passwordResetNotifications,
    ) {
    }

    // ─── v1: User management ───────────────────────────────────────

    public function index(Request $request): View
    {
        $query = User::query()->orderByDesc('created_at');

        $q = trim((string) $request->query('q', ''));

        if ($q !== '') {
            $query->where(fn ($builder) => $builder
                ->where('name', 'like', "%{$q}%")
                ->orWhere('email', 'like', "%{$q}%"));
        }

        $status = (string) $request->query('status', 'all');

        if (in_array($status, ['active', 'disabled', 'locked'], true)) {
            $query->where('status', $status);
        }

        return view('admin.users.index', [
            'users' => $query->paginate(25)->withQueryString(),
            'q' => $q,
            'status' => $status,
            'currentUserId' => Auth::guard('web')->id(),
        ]);
    }

    public function updateStatus(Request $request, string $id): RedirectResponse
    {
        $admin = Auth::guard('web')->user();

        if (!$this->authorization->hasPermission($admin->id, 'users.manage')) {
            return back()->with('error', 'You are not allowed to manage users.');
        }

        if ($admin->id === $id) {
            return back()->with('error', 'You cannot disable your own account.');
        }

        $validator = Validator::make($request->all(), [
            'status' => 'required|in:active,disabled',
        ]);

        if ($validator->fails()) {
            return back()->with('error', 'Invalid status.');
        }

        try {
            $this->identity->setUserStatus($id, $request->input('status'));
        } catch (\Throwable) {
            return back()->with('error', 'Unable to update user status.');
        }

        return back()->with('status', 'User status updated.');
    }

    public function logout(Request $request): RedirectResponse
    {
        Auth::guard('web')->logout();

        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return redirect()->route('login');
    }

    // ─── v3: Admin user creation ──────────────────────────────────

    public function create(): View
    {
        return view('admin.users.create');
    }

    public function store(Request $request): RedirectResponse
    {
        $admin = Auth::guard('web')->user();

        if (!$this->authorization->hasPermission($admin->id, 'users.manage')) {
            return back()->with('error', 'You are not allowed to manage users.');
        }

        $validator = Validator::make($request->all(), [
            'email' => 'required|email|max:255|unique:users,email',
            'name' => 'required|string|max:255',
            'password' => 'nullable|string|min:8',
            'status' => 'required|in:active,disabled',
        ]);

        if ($validator->fails()) {
            return back()->withErrors($validator)->withInput();
        }

        $password = $request->input('password');
        $autoGenerated = false;

        if (empty($password)) {
            $password = Str::random(16);
            $autoGenerated = true;
        } else {
            $hasUppercase = preg_match('/[A-Z]/', $password);
            $hasLowercase = preg_match('/[a-z]/', $password);
            $hasNumber = preg_match('/\d/', $password);
            $hasSpecial = preg_match('/[^A-Za-z0-9]/', $password);

            if (!$hasUppercase || !$hasLowercase || !$hasNumber || !$hasSpecial) {
                return back()->with('error', 'Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character.')->withInput();
            }
        }

        try {
            $user = $this->identity->register($request->input('email'), $password, $request->input('name'));

            if ($request->input('status') === 'disabled') {
                $this->identity->setUserStatus($user->id, 'disabled');
            }

            $this->passwordResetNotifications->sendForgotPasswordLink($user->email);
        } catch (\Throwable $e) {
            return back()->with('error', $e->getMessage())->withInput();
        }

        $message = 'User created successfully.';
        if ($autoGenerated) {
            $message .= " Generated password: {$password}";
        }

        return redirect()->route('admin.users')->with('status', $message);
    }

    // ─── v2: Tenant management ─────────────────────────────────────

    public function tenantsIndex(): View
    {
        $tenants = Tenant::withCount('users')
            ->orderByDesc('created_at')
            ->paginate(25);

        return view('admin.tenants.index', ['tenants' => $tenants]);
    }

    public function tenantsCreate(): View
    {
        return view('admin.tenants.create');
    }

    public function tenantsStore(Request $request): RedirectResponse
    {
        $validator = Validator::make($request->all(), [
            'slug' => 'required|regex:/^[a-z0-9][a-z0-9-]*$/',
            'name' => 'required|string|max:255',
            'app_url' => 'nullable|url|max:255',
            'redirect_origins' => 'nullable|string',
        ]);

        if ($validator->fails()) {
            return back()->withErrors($validator)->withInput();
        }

        $origins = array_values(array_filter(array_map(
            fn (string $url): string => trim($url),
            explode(',', $request->input('redirect_origins', '')),
        )));

        try {
            $this->tenants->createTenant([
                'slug' => $request->input('slug'),
                'name' => $request->input('name'),
                'app_url' => $request->input('app_url'),
                'redirect_origins' => $origins,
            ]);
        } catch (\Throwable $e) {
            return back()->with('error', $e->getMessage())->withInput();
        }

        return redirect()->route('admin.tenants')->with('status', 'Tenant created.');
    }

    public function tenantsShow(Tenant $tenant): View
    {
        $tenant->loadCount('users');

        $members = $tenant->users()
            ->orderBy('email')
            ->paginate(25);

        $nonMembers = User::whereNotIn('id', $tenant->users()->pluck('users.id'))
            ->orderBy('email')
            ->get();

        return view('admin.tenants.show', [
            'tenant' => $tenant,
            'members' => $members,
            'nonMembers' => $nonMembers,
        ]);
    }

    public function tenantsStatus(Request $request, Tenant $tenant): RedirectResponse
    {
        $validator = Validator::make($request->all(), [
            'status' => 'required|in:active,suspended',
        ]);

        if ($validator->fails()) {
            return back()->with('error', 'Invalid status.');
        }

        $targetStatus = $request->input('status');

        try {
            if ($targetStatus === 'suspended') {
                $this->tenants->suspendTenant($tenant->id);
            } else {
                $this->tenants->activateTenant($tenant->id);
            }
        } catch (\Throwable) {
            return back()->with('error', 'Unable to update tenant status.');
        }

        return back()->with('status', "Tenant {$targetStatus}.");
    }

    // ─── v2: Tenant groups + permissions ───────────────────────────

    public function tenantsGroups(Tenant $tenant): View
    {
        $groups = $tenant->userGroups()
            ->with('permissions')
            ->orderBy('name')
            ->get();

        $allPermissions = Permission::orderBy('key')->get();

        $formOptions = $groups->pluck('name', 'id');

        return view('admin.tenants.groups', [
            'tenant' => $tenant,
            'groups' => $groups,
            'allPermissions' => $allPermissions,
            'formOptions' => $formOptions,
        ]);
    }

    public function tenantsGroupsStore(Request $request, Tenant $tenant): RedirectResponse
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|string|max:255',
            'description' => 'nullable|string|max:255',
        ]);

        if ($validator->fails()) {
            return back()->withErrors($validator);
        }

        $existing = UserGroup::where('tenant_id', $tenant->id)
            ->where('name', $request->input('name'))
            ->exists();

        if ($existing) {
            return back()->with('error', 'A group with that name already exists in this tenant.');
        }

        UserGroup::create([
            'name' => $request->input('name'),
            'description' => $request->input('description'),
            'tenant_id' => $tenant->id,
        ]);

        return back()->with('status', 'Group created.');
    }

    public function tenantsGroupsPermissions(Request $request, Tenant $tenant, UserGroup $group): RedirectResponse
    {
        if ($group->tenant_id !== $tenant->id) {
            return back()->with('error', 'Group does not belong to this tenant.');
        }

        $validator = Validator::make($request->all(), [
            'permissions' => 'nullable|array',
            'permissions.*' => 'integer|exists:permissions,id',
        ]);

        if ($validator->fails()) {
            return back()->with('error', 'Invalid permission data.');
        }

        $allowedIds = $request->input('permissions', []);

        DB::transaction(function () use ($group, $tenant, $allowedIds) {
            $allPermissions = Permission::pluck('id');

            foreach ($allPermissions as $permId) {
                $group->permissions()->updateExistingPivot(
                    $permId,
                    ['granted' => in_array($permId, $allowedIds, true), 'tenant_id' => $tenant->id],
                );
            }
        });

        return back()->with('status', 'Permissions updated.');
    }

    // ─── v2: Tenant members ────────────────────────────────────────

    public function tenantsMembersStore(Request $request, Tenant $tenant): RedirectResponse
    {
        $validator = Validator::make($request->all(), [
            'user_id' => 'required|exists:users,id',
            'action' => 'required|in:add,remove',
        ]);

        if ($validator->fails()) {
            return back()->withErrors($validator);
        }

        $userId = $request->input('user_id');
        $action = $request->input('action');

        try {
            if ($action === 'add') {
                $this->tenants->addUserToTenant($userId, $tenant->id);
                return back()->with('status', 'User added to tenant.');
            }

            $this->tenants->removeUserFromTenant($userId, $tenant->id);

            return back()->with('status', 'User removed from tenant.');
        } catch (\Throwable) {
            return back()->with('error', 'Unable to update membership.');
        }
    }
}
