<?php

return [

    'public' => [
        '/api/v1/verify/{certificate_number}',
        '/api/v1/view/{id}',
        '/api/v1/auth/callback',
        '/api/v1/auth/refresh',
        '/api/v1/auth/logout',
    ],

    'catalog' => [
        ['method' => 'GET',    'path' => '/api/v1/events',                        'required_level' => 'read'],
        ['method' => 'POST',   'path' => '/api/v1/events',                        'required_level' => 'write'],
        ['method' => 'GET',    'path' => '/api/v1/events/{id}',                   'required_level' => 'read'],
        ['method' => 'PATCH',  'path' => '/api/v1/events/{id}',                   'required_level' => 'write'],
        ['method' => 'DELETE', 'path' => '/api/v1/events/{id}',                   'required_level' => 'write'],
        ['method' => 'GET',    'path' => '/api/v1/events/{id}/stats',             'required_level' => 'read'],
        ['method' => 'POST',   'path' => '/api/v1/events/{id}/clone-template',    'required_level' => 'write'],
        ['method' => 'POST',   'path' => '/api/v1/events/{id}/clone-email-template', 'required_level' => 'write'],
        ['method' => 'POST',   'path' => '/api/v1/events/{id}/bulk-issue',        'required_level' => 'write'],
        ['method' => 'POST',   'path' => '/api/v1/events/{id}/reissue',           'required_level' => 'admin'],
        ['method' => 'GET',    'path' => '/api/v1/events/{id}/revoke-expired',    'required_level' => 'read'],
        ['method' => 'POST',   'path' => '/api/v1/events/{id}/revoke-expired',    'required_level' => 'admin'],
        ['method' => 'POST',   'path' => '/api/v1/events/{id}/issue-completed',   'required_level' => 'write'],
        ['method' => 'GET',    'path' => '/api/v1/events/{id}/attendees',         'required_level' => 'read'],
        ['method' => 'POST',   'path' => '/api/v1/events/{id}/attendees',         'required_level' => 'write'],
        ['method' => 'POST',   'path' => '/api/v1/events/{id}/attendees/import',  'required_level' => 'write'],
        ['method' => 'PATCH',  'path' => '/api/v1/attendees/{id}',                'required_level' => 'write'],
        ['method' => 'DELETE', 'path' => '/api/v1/attendees/{id}',                'required_level' => 'write'],
        ['method' => 'DELETE', 'path' => '/api/v1/attendees/{id}/with-cert',      'required_level' => 'admin'],
        ['method' => 'GET',    'path' => '/api/v1/attendees/{id}/delete-preview', 'required_level' => 'read'],
        ['method' => 'GET',    'path' => '/api/v1/attendees/{id}/file-data',      'required_level' => 'read'],
        ['method' => 'GET',    'path' => '/api/v1/templates',                     'required_level' => 'read'],
        ['method' => 'POST',   'path' => '/api/v1/templates',                     'required_level' => 'write'],
        ['method' => 'GET',    'path' => '/api/v1/templates/{id}',                'required_level' => 'read'],
        ['method' => 'PATCH',  'path' => '/api/v1/templates/{id}',                'required_level' => 'write'],
        ['method' => 'DELETE', 'path' => '/api/v1/templates/{id}',                'required_level' => 'write'],
        ['method' => 'POST',   'path' => '/api/v1/certificates',                  'required_level' => 'write'],
        ['method' => 'POST',   'path' => '/api/v1/certificates/bulk',             'required_level' => 'write'],
        ['method' => 'POST',   'path' => '/api/v1/certificates/upload',           'required_level' => 'write'],
        ['method' => 'GET',    'path' => '/api/v1/certificates',                  'required_level' => 'read'],
        ['method' => 'GET',    'path' => '/api/v1/certificates/{id}',             'required_level' => 'read'],
        ['method' => 'GET',    'path' => '/api/v1/certificates/{id}/pdf',         'required_level' => 'read'],
        ['method' => 'GET',    'path' => '/api/v1/certificates/{id}/download',    'required_level' => 'read'],
        ['method' => 'POST',   'path' => '/api/v1/certificates/{id}/revoke',      'required_level' => 'admin'],
        ['method' => 'DELETE', 'path' => '/api/v1/certificates/{id}',             'required_level' => 'admin'],
        ['method' => 'POST',   'path' => '/api/v1/certificates/{id}/email',       'required_level' => 'write'],
        ['method' => 'GET',    'path' => '/api/v1/certificates/{id}/email-logs',  'required_level' => 'read'],
        ['method' => 'POST',   'path' => '/api/v1/certificates/{id}/reissue',     'required_level' => 'admin'],
        ['method' => 'POST',   'path' => '/api/v1/certificates/expire',           'required_level' => 'admin'],
        ['method' => 'GET',    'path' => '/api/v1/certificates/qr',               'required_level' => 'read'],
        ['method' => 'GET',    'path' => '/api/v1/me/certificates',               'required_level' => 'read'],
        ['method' => 'GET',    'path' => '/api/v1/me/certificates/{id}',          'required_level' => 'read'],
        ['method' => 'GET',    'path' => '/api/v1/me/events',                     'required_level' => 'read'],
        ['method' => 'GET',    'path' => '/api/v1/me/templates',                  'required_level' => 'read'],
        ['method' => 'GET',    'path' => '/api/v1/dashboard/stats',               'required_level' => 'read'],
        ['method' => 'GET',    'path' => '/api/v1/dashboard/activity',            'required_level' => 'read'],
        ['method' => 'GET',    'path' => '/api/v1/admin/audit-logs',              'required_level' => 'admin'],
        ['method' => 'GET',    'path' => '/api/v1/admin/audit-logs/export',       'required_level' => 'admin'],
    ],

];
